### ISSUE TITLE
ARM64 / M1 Chrome Binary - Failed to Download

### ISSUE THREAD

**Issue by thomaswoj** [laravel/dusk#1000]
- Dusk Version: 6.25.1
- Laravel Version: 9.17
- PHP Version: 8.1.8
- Database Driver & Version: Chrome browser 106.0.5249.61 macOS 12.4 M1

### Description:
Dusk not able to download latest Chrome driver binary

### Steps To Reproduce:
- attempting `php artisan dusk:chrome-driver` results in error
```
file_get_contents(https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip): 
Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found 
 ```

 ### Issue
 - looks like the filenames of the Chrome binaries have been changed (see https://chromedriver.storage.googleapis.com/)
 - older m1 versions were named in format : `106.0.5249.21/chromedriver_mac64_m1.zip`
 - new versions appear to be in format : `106.0.5249.61/chromedriver_mac_arm64.zip`
 
 ### Workaround
 - For now, I just switched out the slug attribute inside `Laravel\Dusk\Console\ChromeDriverCommand.php` on my local, so the actual fix probably just needs a catch somewhere to check alternative filename endings when trying to download. 
 
 ```php
    /**
     * Download slugs for the available operating systems.
     *
     * @var array
     */
    protected $slugs = [
        'linux' => 'linux64',
        'mac' => 'mac64',
        'mac-intel' => 'mac64',
        'mac-arm' => 'mac_arm64',
//        'mac-arm' => 'mac64_m1',
        'win' => 'win32',
    ];
 ```

**Comment by mdsinghmalik** [comment]
This is very annoying and breaking our test pipelines. Please fix this ASAP.

**Comment by driesvints** [comment]
@thomaswoj thanks for reporting this. I released both 7.x and 6.x with a fix.

@mdsinghmalik next time feel free to send in a PR instead of complaining.

**Comment by om4james** [comment]
Thank you @driesvints

**Comment by om4james** [comment]
> This is very annoying and breaking our test pipelines. Please fix this ASAP.

Hi @mdsinghmalik, I just wanted to provide my perspective here.

Whilst this issue is indeed annoying (our CI pipelines broke too), the cause of the problem wasn't Laravel.

The issue was caused by the Google Chrome Driver URLs being changed at Google's end, and many downstream ecosystems (such as Laravel, Ruby on Rails, and more) all had to implement changes as a result of Google changing things.

I think the fact that Laravel (in this case @driesvints) implemented a fix and released a new version so quickly is fantastic.

They certainly weren't obligated to do this so quickly.

This package is open source at the end of the day, so anyone (including you or I) is always welcome to submit a PR to fix an issue like this one.

Or if fixing it yourself isn't an option, then being kind instead of complaining will also ultimately help everyone in the community 😎

Thank you @driesvints for your swift action to resolve this, I (and no doubt others in the Laravel community) really appreciate it.

**Comment by voidgraphics** [comment]
If like me you're still seeing this error after updating dusk to `v7.1.1` or `v6.25.2`, you probably need to update Google Chrome. It needs to be at version 106.x or higher for the error to go away.
